### ISSUE TITLE
Minor tweaks

### ISSUE THREAD

**Issue by XhmikosR** [ScottHelme/report-uri-bugs#3]
I'd like to suggest one minor improvement for https://report-uri.io/home/tools.

```css
.service-box-v1 a {
    display: inline-block;
}
```

This will make the whole box clickable without the empty space between `h2` and `a`.

You can also remove the stuff after `DOCTYPE`.

Finally, you should remove `chrome=1` from `<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">` since that has been discontinued.
